export const CREATE_CLIENT_REQUEST = "CREATE_CLIENT_REQUEST";
export const CREATE_CLIENT_SUCCESS = "CREATE_CLIENT_SUCCESS";
export const CREATE_CLIENT_FAIL = "CREATE_CLIENT_FAIL";
export const CREATE_CLIENT_RESET = "CREATE_CLIENT_RESET";

export const GET_CLIENT_REQUEST = "GET_CLIENT_REQUEST";
export const GET_CLIENT_SUCCESS = "GET_CLIENT_SUCCESS";
export const GET_CLIENT_FAIL = "GET_CLIENT_FAIL";
export const GET_CLIENT_RESET = "GET_CLIENT_RESET";

export const UPDATE_CLIENT_REQUEST = "UPDATE_CLIENT_REQUEST";
export const UPDATE_CLIENT_SUCCESS = "UPDATE_CLIENT_SUCCESS";
export const UPDATE_CLIENT_FAIL = "UPDATE_CLIENT_FAIL";
export const UPDATE_CLIENT_RESET = "UPDATE_CLIENT_RESET";

export const DELETE_CLIENT_REQUEST = "DELETE_CLIENT_REQUEST";
export const DELETE_CLIENT_SUCCESS = "DELETE_CLIENT_SUCCESS";
export const DELETE_CLIENT_FAIL = "DELETE_CLIENT_FAIL";
export const DELETE_CLIENT_RESET = "DELETE_CLIENT_RESET";

export const GET_SINGLE_CLIENT_REQUEST = "GET_SINGLE_CLIENT_REQUEST";
export const GET_SINGLE_CLIENT_SUCCESS = "GET_SINGLE_CLIENT_SUCCESS";
export const GET_SINGLE_CLIENT_FAIL = "GET_SINGLE_CLIENT_FAIL";
export const GET_SINGLE_CLIENT_RESET = "GET_SINGLE_CLIENT_RESET";

export const ASSIGN_ECLIENT_REQUEST = "ASSIGN_ECLIENT_REQUEST";
export const ASSIGN_ECLIENT_SUCCESS = "ASSIGN_ECLIENT_SUCCESS";
export const ASSIGN_ECLIENT_FAIL = "ASSIGN_ECLIENT_FAIL";
export const ASSIGN_ECLIENT_RESET = "ASSIGN_ECLIENT_RESET";

export const REMOVE_ECLIENT_REQUEST = "REMOVE_ECLIENT_REQUEST";
export const REMOVE_ECLIENT_SUCCESS = "REMOVE_ECLIENT_SUCCESS";
export const REMOVE_ECLIENT_FAIL = "REMOVE_ECLIENT_FAIL";
export const REMOVE_ECLIENT_RESET = "REMOVE_ECLIENT_RESET";
