export const CREATE_EVENT_REQUEST = "CREATE_EVENT_REQUEST";
export const CREATE_EVENT_SUCCESS = "CREATE_EVENT_SUCCESS";
export const CREATE_EVENT_FAIL = "CREATE_EVENT_FAIL";
export const CREATE_EVENT_RESET = "CREATE_EVENT_RESET";

export const GET_EVENT_REQUEST = "GET_EVENT_REQUEST";
export const GET_EVENT_SUCCESS = "GET_EVENT_SUCCESS";
export const GET_EVENT_FAIL = "GET_EVENT_FAIL";
export const GET_EVENT_RESET = "GET_EVENT_RESET";

export const UPDATE_EVENT_REQUEST = "UPDATE_EVENT_REQUEST";
export const UPDATE_EVENT_SUCCESS = "UPDATE_EVENT_SUCCESS";
export const UPDATE_EVENT_FAIL = "UPDATE_EVENT_FAIL";
export const UPDATE_EVENT_RESET = "UPDATE_EVENT_RESET";

export const DELETE_EVENT_REQUEST = "DELETE_EVENT_REQUEST";
export const DELETE_EVENT_SUCCESS = "DELETE_EVENT_SUCCESS";
export const DELETE_EVENT_FAIL = "DELETE_EVENT_FAIL";
export const DELETE_EVENT_RESET = "DELETE_EVENT_RESET";

export const PUBLISH_EVENT_REQUEST = "PUBLISH_EVENT_REQUEST";
export const PUBLISH_EVENT_SUCCESS = "PUBLISH_EVENT_SUCCESS";
export const PUBLISH_EVENT_FAIL = "PUBLISH_EVENT_FAIL";
export const PUBLISH_EVENT_RESET = "PUBLISH_EVENT_RESET";

export const GET_ALL_EVENT_REQUEST = "GET_ALL_EVENT_REQUEST";
export const GET_ALL_EVENT_SUCCESS = "GET_ALL_EVENT_SUCCESS";
export const GET_ALL_EVENT_FAIL = "GET_ALL_EVENT_FAIL";
export const GET_ALL_EVENT_RESET = "GET_ALL_EVENT_RESET";
