export const CREATE_LOCATION_REQUEST = "CREATE_LOCATION_REQUEST";
export const CREATE_LOCATION_SUCCESS = "CREATE_LOCATION_SUCCESS";
export const CREATE_LOCATION_FAIL = "CREATE_LOCATION_FAIL";
export const CREATE_LOCATION_RESET = "CREATE_LOCATION_RESET";

export const GET_LOCATION_REQUEST = "GET_LOCATION_REQUEST";
export const GET_LOCATION_SUCCESS = "GET_LOCATION_SUCCESS";
export const GET_LOCATION_FAIL = "GET_LOCATION_FAIL";
export const GET_LOCATION_RESET = "GET_LOCATION_RESET";

export const UPDATE_LOCATION_REQUEST = "UPDATE_LOCATION_REQUEST";
export const UPDATE_LOCATION_SUCCESS = "UPDATE_LOCATION_SUCCESS";
export const UPDATE_LOCATION_FAIL = "UPDATE_LOCATION_FAIL";
export const UPDATE_LOCATION_RESET = "UPDATE_LOCATION_RESET";

export const DELETE_LOCATION_REQUEST = "DELETE_LOCATION_REQUEST";
export const DELETE_LOCATION_SUCCESS = "DELETE_LOCATION_SUCCESS";
export const DELETE_LOCATION_FAIL = "DELETE_LOCATION_FAIL";
export const DELETE_LOCATION_RESET = "DELETE_LOCATION_RESET";
