export const CREATE_REPORT_REQUEST = "CREATE_REPORT_REQUEST";
export const CREATE_REPORT_SUCCESS = "CREATE_REPORT_SUCCESS";
export const CREATE_REPORT_FAIL = "CREATE_REPORT_FAIL";
export const CREATE_REPORT_RESET = "CREATE_REPORT_RESET";

export const GET_REPORT_REQUEST = "GET_REPORT_REQUEST";
export const GET_REPORT_SUCCESS = "GET_REPORT_SUCCESS";
export const GET_REPORT_FAIL = "GET_REPORT_FAIL";
export const GET_REPORT_RESET = "GET_REPORT_RESET";

export const UPDATE_REPORT_REQUEST = "UPDATE_REPORT_REQUEST";
export const UPDATE_REPORT_SUCCESS = "UPDATE_REPORT_SUCCESS";
export const UPDATE_REPORT_FAIL = "UPDATE_REPORT_FAIL";
export const UPDATE_REPORT_RESET = "UPDATE_REPORT_RESET";

export const DELETE_REPORT_REQUEST = "DELETE_REPORT_REQUEST";
export const DELETE_REPORT_SUCCESS = "DELETE_REPORT_SUCCESS";
export const DELETE_REPORT_FAIL = "DELETE_REPORT_FAIL";
export const DELETE_REPORT_RESET = "DELETE_REPORT_RESET";

export const GEN_REPORT_REQUEST = "GEN_REPORT_REQUEST";
export const GEN_REPORT_SUCCESS = "GEN_REPORT_SUCCESS";
export const GEN_REPORT_FAIL = "GEN_REPORT_FAIL";
export const GEN_REPORT_RESET = "GEN_REPORT_RESET";
