export const CREATE_ROTA_REQUEST = "CREATE_ROTA_REQUEST";
export const CREATE_ROTA_SUCCESS = "CREATE_ROTA_SUCCESS";
export const CREATE_ROTA_FAIL = "CREATE_ROTA_FAIL";
export const CREATE_ROTA_RESET = "CREATE_ROTA_RESET";

export const GET_ROTA_REQUEST = "GET_ROTA_REQUEST";
export const GET_ROTA_SUCCESS = "GET_ROTA_SUCCESS";
export const GET_ROTA_FAIL = "GET_ROTA_FAIL";
export const GET_ROTA_RESET = "GET_ROTA_RESET";

export const UPDATE_ROTA_REQUEST = "UPDATE_ROTA_REQUEST";
export const UPDATE_ROTA_SUCCESS = "UPDATE_ROTA_SUCCESS";
export const UPDATE_ROTA_FAIL = "UPDATE_ROTA_FAIL";
export const UPDATE_ROTA_RESET = "UPDATE_ROTA_RESET";

export const DELETE_ROTA_REQUEST = "DELETE_ROTA_REQUEST";
export const DELETE_ROTA_SUCCESS = "DELETE_ROTA_SUCCESS";
export const DELETE_ROTA_FAIL = "DELETE_ROTA_FAIL";
export const DELETE_ROTA_RESET = "DELETE_ROTA_RESET";
