export const CREATE_SCHEDULE_REQUEST = "CREATE_SCHEDULE_REQUEST";
export const CREATE_SCHEDULE_SUCCESS = "CREATE_SCHEDULE_SUCCESS";
export const CREATE_SCHEDULE_FAIL = "CREATE_SCHEDULE_FAIL";
export const CREATE_SCHEDULE_RESET = "CREATE_SCHEDULE_RESET";

export const GET_SCHEDULE_REQUEST = "GET_SCHEDULE_REQUEST";
export const GET_SCHEDULE_SUCCESS = "GET_SCHEDULE_SUCCESS";
export const GET_SCHEDULE_FAIL = "GET_SCHEDULE_FAIL";
export const GET_SCHEDULE_RESET = "GET_SCHEDULE_RESET";

export const UPDATE_SCHEDULE_REQUEST = "UPDATE_SCHEDULE_REQUEST";
export const UPDATE_SCHEDULE_SUCCESS = "UPDATE_SCHEDULE_SUCCESS";
export const UPDATE_SCHEDULE_FAIL = "UPDATE_SCHEDULE_FAIL";
export const UPDATE_SCHEDULE_RESET = "UPDATE_SCHEDULE_RESET";

export const DELETE_SCHEDULE_REQUEST = "DELETE_SCHEDULE_REQUEST";
export const DELETE_SCHEDULE_SUCCESS = "DELETE_SCHEDULE_SUCCESS";
export const DELETE_SCHEDULE_FAIL = "DELETE_SCHEDULE_FAIL";
export const DELETE_SCHEDULE_RESET = "DELETE_SCHEDULE_RESET";

export const DUB_SCHEDULE_REQUEST = "DUB_SCHEDULE_REQUEST";
export const DUB_SCHEDULE_SUCCESS = "DUB_SCHEDULE_SUCCESS";
export const DUB_SCHEDULE_FAIL = "DUB_SCHEDULE_FAIL";
export const DUB_SCHEDULE_RESET = "DUB_SCHEDULE_RESET";
