export const ACTIVATE_ACCT_REQUEST = "ACTIVATE_ACCT_REQUEST";
export const ACTIVATE_ACCT_SUCCESS = "ACTIVATE_ACCT_SUCCESS";
export const ACTIVATE_ACCT_FAIL = "ACTIVATE_ACCT_FAIL";
export const ACTIVATE_ACCT_RESET = "ACTIVATE_ACCT_RESET";

export const DELETE_ACCT_REQUEST = "DELETE_ACCT_REQUEST";
export const DELETE_ACCT_SUCCESS = "DELETE_ACCT_SUCCESS";
export const DELETE_ACCT_FAIL = "DELETE_ACCT_FAIL";
export const DELETE_ACCT_RESET = "DELETE_ACCT_RESET";

export const GET_T_REQUEST = "GET_T_REQUEST";
export const GET_T_SUCCESS = "GET_T_SUCCESS";
export const GET_T_FAIL = "GET_T_FAIL";
export const GET_T_RESET = "GET_T_RESET";
